[tool.poetry]
name = ""
version = "0.0.1"
description = ""
authors = ["Vladimir faiver90@gmail.com"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.118.3"
ruff = "^0.14.1"


[tool.poetry.group.dev.dependencies]
alembic = "^1.16.4"
pytest = "^8.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["E501",
    "B008",
    "B904",
    "E402",
    "B018",
    "E741",
    "UP035",
    "F841",
    "B026",
    "B024",
    "UP006",
    "UP008"]
fixable = ["ALL"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.black]
line-length = 88
target-version = ["py311"]